services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.13.0
    command: >
      mlflow server
      --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --allowed-hosts "*"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - models_data:/app/models
    profiles:
      - train

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      API_URL: http://api:8000
    volumes:
      - models_data:/app/models:ro
    depends_on:
      - mlflow
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      API_URL: http://api:8000
      API_DOCS_URL: http://88.96.61.63:8000/docs
      MLFLOW_EXTERNAL_URL: http://88.96.61.63:5000
      GITHUB_URL: https://github.com/Rymfouzari/mlops-iabd-esgi-FOUZARI
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy

  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Rym
      --lastname Fouzari
      --role Admin
      --email admin@example.com || true;
      airflow scheduler &
      airflow webserver --host 0.0.0.0 --port 8080
      "
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      PYTHONPATH: /opt/airflow/todo
      MLFLOW_TRACKING_URI: http://mlflow:5000
      API_URL: http://api:8000
      N_TRIALS: "5"
      CV: "2"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./todo:/opt/airflow/todo
      - ./data:/opt/airflow/data
      - models_data:/opt/airflow/models
    depends_on:
      api:
        condition: service_healthy
      mlflow:
        condition: service_started

volumes:
  mlflow_data:
  models_data:
