FROM apache/airflow:2.10.5-python3.12

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends git libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY pyproject.toml ./
COPY uv.lock ./

RUN pip install --no-cache-dir . \
    && pip install --no-cache-dir httpx scikit-learn mlflow optuna xgboost lightgbm
