FROM apache/airflow:2.10.5-python3.12

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends git libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    httpx \
    mlflow \
    optuna \
    scikit-learn \
    xgboost \
    lightgbm \
    pandas \
    numpy
